### ISSUE TITLE
Scapy win32 2.7

### ISSUE THREAD

**Issue by nkanish2002** [Kondziowy/scapy_win64#1]
Hi, this is not actually a issue, but I have created some Windows executables for Scapy 2.2.0-dev for a 32bit python2.7 setup. Can you add those to this repo?

Link: https://drive.google.com/folderview?id=0BzE52d6x4xe3QkRVMF9sR1d2d3c&usp=sharing

Thanks.

P.S. I had to create this issue since there is no way to contact you via StackOverflow or github. I am sorry for any inconvenience.

**Comment by Kondziowy** [comment]
Added them. Thanks! Did you make any source changes or did it compile clean?

**Comment by nkanish2002** [comment]
No source changes and a very clean compile.
